//! Writeback metadata cache.
//!
//! Eliminates per-FUSE-op RPC round-trip cost on the write path. Each
//! inbound op updates `InodeTable` / `DirCache` immediately, upserts an
//! intent into the queue, and returns success to the kernel. Worker tasks
//! drain the queue: NSS namespace mutations batch into one `InodeBatch`
//! RPC, BSS block writes batch into one `BssBatch`, and per-file commit
//! ordering A->B->C->D is enforced by the per-inode pipeline.
//!
//! Initial scope: exclusive-writer regular files, `create`, `mkdir`,
//! regular-file `write`, `flush` / `release`, `fsync`, and post-create
//! non-size `setattr`. Default mode only. One active remote generation
//! per file. Stage A CAS conflict ⇒ fail/taint, no transparent rebase.
//! All other operations route to the existing strict path.
//!
//! This module owns the intent map, the generation counter, the stage
//! enum, and the per-file pipeline state. Worker scheduling and FUSE op
//! integration are layered on top.

#![allow(dead_code)] // Permissive while the queue is wired into VfsCore.

use bytes::Bytes;
use data_types::DataBlobGuid;
use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::sync::Mutex;
use std::time::Instant;

/// Pipeline generation number. Monotonic per inode. Tracks the cycle a
/// queued intent belongs to, matching the file's `blob_version` for that
/// cycle.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct Generation(pub u64);

impl Generation {
    pub fn next(self) -> Self {
        Self(self.0 + 1)
    }
}

/// Identifier for a queued intent. Opaque, generated by the queue.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct IntentId(u64);

/// File-handle id stamped on every intent that originated from a write
/// op so deferred errors can be routed back to the closing fh.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct FhId(pub u64);

/// S3 key (the path, e.g. `/foo/bar/baz`). Owned because intents may
/// outlive the FUSE op that produced them.
pub type S3Key = String;

/// Intent lifecycle state. Today `Pending -> InFlight -> Committed`
/// or `Pending -> InFlight -> Failed`. `Failed` records deferred EIO
/// on owning fhs and taints the inode.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IntentState {
    /// Queued but not yet picked by a worker. Coalescable.
    Pending,
    /// Worker has begun shipping this intent. Frozen against further
    /// mutation; new arrivals coalesce into the next generation (or
    /// backpressure in the initial scope).
    InFlight,
    /// Successfully committed remotely.
    Committed,
    /// Permanent failure or retry exhausted. Surfaces as deferred EIO
    /// on owning fhs.
    Failed,
}

/// Stage in the per-file commit pipeline. Workers pop batches by
/// stage so cross-file batch density is preserved while per-file
/// ordering A->B->C->D is enforced.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Stage {
    /// NSS CAS publishes new blob_version. Bumps `Generation`.
    A,
    /// BSS block writes at the published version.
    B,
    /// BSS parent inode update (commits new total_size).
    C,
    /// NSS lazy size update (best-effort).
    D,
}

/// Inode operation captured by an `InodeIntent`. Initial scope only
/// enables `PutInode` and `SetAttr`; later phases add `Unlink`,
/// `Rmdir`, `RenameFile`, `RenameDir`, `Link`, `Symlink`, `Mknod`,
/// and `CommitClaim`.
#[derive(Debug, Clone)]
pub enum InodeOp {
    PutInode {
        parent_key: S3Key,
        name: String,
        layout_bytes: Bytes,
    },
    SetAttr {
        key: S3Key,
        attrs: AttrMutation,
    },
}

/// Subset of inode attributes mutable via `setattr` in the initial
/// scope (non-size only -- size changes route to strict).
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct AttrMutation {
    pub mode: Option<u32>,
    pub uid: Option<u32>,
    pub gid: Option<u32>,
    pub atime_secs: Option<u64>,
    pub mtime_secs: Option<u64>,
}

impl AttrMutation {
    /// Field-merge: `other`'s populated fields overwrite ours.
    /// Non-overlapping fields from `self` are preserved. Used by the
    /// SetAttr+SetAttr coalescing rule.
    pub fn merge_from(&mut self, other: &AttrMutation) {
        if other.mode.is_some() {
            self.mode = other.mode;
        }
        if other.uid.is_some() {
            self.uid = other.uid;
        }
        if other.gid.is_some() {
            self.gid = other.gid;
        }
        if other.atime_secs.is_some() {
            self.atime_secs = other.atime_secs;
        }
        if other.mtime_secs.is_some() {
            self.mtime_secs = other.mtime_secs;
        }
    }

    pub fn is_empty(&self) -> bool {
        self.mode.is_none()
            && self.uid.is_none()
            && self.gid.is_none()
            && self.atime_secs.is_none()
            && self.mtime_secs.is_none()
    }
}

/// Block operation captured by a `BlockIntent`. Initial scope only
/// enables `PutDataBlob`; range ops (`DeleteBlocks`, `ReserveBlocks`)
/// and `BlockState::Delete` arrive with the truncate / fallocate /
/// PUNCH_HOLE phase.
#[derive(Debug, Clone)]
pub enum BlockOp {
    PutDataBlob {
        blob_id: DataBlobGuid,
        block_num: u32,
        version: u64,
        body: Bytes,
        checksum: u64,
    },
}

/// One namespace mutation queued for the per-file pipeline.
#[derive(Debug, Clone)]
pub struct InodeIntent {
    pub op: InodeOp,
    pub generation: Generation,
    pub deps: Vec<IntentId>,
    pub state: IntentState,
    pub fhs: Vec<FhId>,
    pub enqueued_at: Instant,
}

/// One block write queued for Stage B. Keyed by `(blob, block, gen)`.
#[derive(Debug, Clone)]
pub struct BlockIntent {
    pub op: BlockOp,
    pub generation: Generation,
    pub deps: Vec<IntentId>,
    pub state: IntentState,
    pub fhs: Vec<FhId>,
    pub enqueued_at: Instant,
}

/// Stage C — BSS parent inode update. One per file per generation.
#[derive(Debug, Clone)]
pub struct ParentIntent {
    pub blob_id: DataBlobGuid,
    pub inode: u64,
    pub generation: Generation,
    pub parent_inode_meta: Bytes,
    pub fhs: Vec<FhId>,
    pub state: IntentState,
    pub enqueued_at: Instant,
}

/// Per-file commit pipeline state.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FileCommitStage {
    Idle,
    StageAQueued,
    StageACommitted,
    StageBInFlight { blocks_remaining: u32 },
    StageBCommitted,
    StageCQueued,
    StageCCommitted,
    StageDQueued,
    Done,
}

/// Per-cycle terminal size. `Building` accepts further writes;
/// `Sealed` is frozen at Stage A issue and is what Stage C reads.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TerminalSize {
    Building { file_size: u64, block_count: u32 },
    Sealed { file_size: u64, block_count: u32 },
}

impl TerminalSize {
    pub fn file_size(&self) -> u64 {
        match self {
            TerminalSize::Building { file_size, .. } | TerminalSize::Sealed { file_size, .. } => {
                *file_size
            }
        }
    }

    pub fn block_count(&self) -> u32 {
        match self {
            TerminalSize::Building { block_count, .. }
            | TerminalSize::Sealed { block_count, .. } => *block_count,
        }
    }

    pub fn is_sealed(&self) -> bool {
        matches!(self, TerminalSize::Sealed { .. })
    }
}

/// Per-cycle pipeline record. One per (inode, generation) at any
/// time the cycle is dirty.
#[derive(Debug, Clone)]
pub struct CyclePipelineState {
    pub generation: Generation,
    pub stage: FileCommitStage,
    pub terminal_size: TerminalSize,
    /// fhs that have contributed any intent to this cycle. Walked on
    /// FUSE_RELEASE to seal still-Pending stages and detach error
    /// routing onto the inode.
    pub contributors: BTreeSet<FhId>,
}

impl CyclePipelineState {
    pub fn new(generation: Generation, file_size: u64, block_count: u32) -> Self {
        Self {
            generation,
            stage: FileCommitStage::Idle,
            terminal_size: TerminalSize::Building {
                file_size,
                block_count,
            },
            contributors: BTreeSet::new(),
        }
    }

    /// Apply a write that grows / changes the cycle's terminal size.
    /// Idempotent: only updates if the new value is larger.
    pub fn note_write(&mut self, new_file_size: u64, new_block_count: u32, fh: FhId) {
        self.contributors.insert(fh);
        if let TerminalSize::Building {
            file_size,
            block_count,
        } = &mut self.terminal_size
        {
            if new_file_size > *file_size {
                *file_size = new_file_size;
            }
            if new_block_count > *block_count {
                *block_count = new_block_count;
            }
        }
        // Sealed cycles ignore further writes -- those go to gen+1
        // (full target) or backpressure (initial scope).
    }

    /// Seal `terminal_size` at Stage A issue. Once sealed, future
    /// writes for this generation are rejected (initial scope:
    /// backpressured at the queue's enqueue layer).
    pub fn seal(&mut self) {
        if let TerminalSize::Building {
            file_size,
            block_count,
        } = self.terminal_size
        {
            self.terminal_size = TerminalSize::Sealed {
                file_size,
                block_count,
            };
        }
    }
}

/// Coarse capacity / age telemetry. Updated by enqueue / drain.
#[derive(Debug, Default, Clone, Copy)]
pub struct QueueState {
    pub depth: u64,
    pub bytes_buffered: u64,
    pub deferred_errors: u64,
    pub backpressure_waits: u64,
    pub dependency_stalls: u64,
    /// Set by unmount; rejects new FUSE ops with ENOTCONN.
    pub enqueue_blocked: bool,
}

/// Coalescing outcome reported back to the caller of `upsert_*`. Lets
/// tests and the FUSE-op layer assert how an op composed against
/// existing state.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CoalesceOutcome {
    /// Brand-new intent installed.
    Inserted,
    /// Existing Pending intent's body / fields replaced in place.
    ReplacedInPlace,
    /// Two ops merged into a single richer op (e.g. PutInode+SetAttr).
    Merged,
    /// Caller must backpressure: the same key has an InFlight intent
    /// at a prior generation and the initial scope forbids successor
    /// generations.
    BackpressureRequired,
}

/// The writeback queue. Wrapped behind a Mutex so it can be shared
/// across compio tasks; the critical sections are short
/// (HashMap upsert + index update). A finer-grained scheme is a
/// later optimization.
pub struct WritebackQueue {
    inner: Mutex<QueueInner>,
}

struct QueueInner {
    inode_intents: HashMap<(S3Key, Generation), InodeIntent>,
    block_intents: HashMap<(DataBlobGuid, u32, Generation), BlockIntent>,
    parent_intents: HashMap<(DataBlobGuid, Generation), ParentIntent>,

    inodes_by_parent: HashMap<S3Key, BTreeSet<IntentId>>,
    intents_by_stage: BTreeMap<Stage, BTreeSet<IntentId>>,

    /// Per-inode pipeline records, keyed by inode number. Each inode
    /// can have multiple cycles in flight (full target); the initial
    /// scope holds at most one active remote generation, but the map
    /// shape carries the generation explicitly so the same code path
    /// serves both phases.
    file_pipeline: HashMap<u64, BTreeMap<Generation, CyclePipelineState>>,

    /// Active generation per inode — the gen new writes are routed to.
    active_generation: HashMap<u64, Generation>,

    /// Dependency edges. `dep_predecessors[d]` is the set of intents
    /// `d` is waiting on; `dep_dependents[p]` is the inverse map for
    /// fast removal when `p` commits.
    dep_predecessors: HashMap<IntentId, BTreeSet<IntentId>>,
    dep_dependents: HashMap<IntentId, BTreeSet<IntentId>>,

    /// Per-inode errseq + tainted flag for deferred-error routing.
    errseq: HashMap<u64, InodeErrorState>,

    /// Per-inode pending-data overlay. Populated as FUSE_WRITE
    /// arrives; cleared as Stage B intents commit.
    pending_overlay: HashMap<u64, PendingOverlay>,

    next_intent_id: u64,
    state: QueueState,
}

/// Errseq counter and taint flag tracked per inode. The fsyncgate
/// model: every fh stamps its `last_seen_errseq` after each fsync,
/// and the next fsync surfaces EIO iff the inode's counter has
/// advanced. Tainting is sticky -- it persists until close+reopen.
#[derive(Debug, Default, Clone, Copy)]
pub struct InodeErrorState {
    pub errseq: u32,
    pub tainted: bool,
}

/// Per-fh last-seen errseq counter. Owned by the file-handle table;
/// the queue does not store it.
#[derive(Debug, Default, Clone, Copy)]
pub struct FhErrSeq(pub u32);

/// Per-block content for the pending-data overlay. Mirrors the
/// per-handle WriteBuffer's `BlockState` shape so the cross-handle
/// view stays in sync with what individual writers buffered.
#[derive(Debug, Clone)]
pub enum OverlayBlockState {
    Cached(Bytes),
    Rewrite(Bytes),
    /// Reserved for the truncate / fallocate phase; not produced by
    /// the initial Phase scope.
    Delete,
}

/// Inode-level pending-data overlay. Aggregates buffered writes
/// across every fh open on the inode so a reader on a different fh
/// (same instance) sees the same bytes as the writer.
///
/// The overlay shrinks as Stage B intents reach Committed and
/// drops back to empty when the inode goes idle.
#[derive(Debug, Default, Clone)]
pub struct PendingOverlay {
    pub file_size: u64,
    pub blocks: BTreeMap<u32, OverlayBlockState>,
}

impl PendingOverlay {
    /// Resolve a single block. Returns `Some(bytes)` if the overlay
    /// has buffered content for that block, `None` for a miss
    /// (caller falls through to disk cache + BSS).
    pub fn lookup_block(&self, block: u32) -> Option<&Bytes> {
        match self.blocks.get(&block)? {
            OverlayBlockState::Cached(b) | OverlayBlockState::Rewrite(b) => Some(b),
            OverlayBlockState::Delete => None,
        }
    }

    /// `true` iff the block is buffered as a hole (PUNCH_HOLE /
    /// shrink that hasn't yet reached BSS). Reads must serve zeros.
    pub fn block_is_hole(&self, block: u32) -> bool {
        matches!(self.blocks.get(&block), Some(OverlayBlockState::Delete))
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StageAdvanceError {
    CycleMissing,
    InvalidTransition {
        from: FileCommitStage,
        to: FileCommitStage,
    },
}

/// Validates a single per-file pipeline transition. Workers must drive
/// stages in this order; skipping a stage or going backwards is
/// rejected at the queue layer.
fn is_valid_stage_transition(from: FileCommitStage, to: FileCommitStage) -> bool {
    use FileCommitStage::*;
    matches!(
        (from, to),
        (Idle, StageAQueued)
            | (StageAQueued, StageACommitted)
            | (StageACommitted, StageBInFlight { .. })
            | (StageBInFlight { .. }, StageBInFlight { .. })
            | (StageBInFlight { .. }, StageBCommitted)
            | (StageBCommitted, StageCQueued)
            | (StageCQueued, StageCCommitted)
            | (StageCCommitted, StageDQueued)
            | (StageDQueued, Done)
            // Failed cycles can short-circuit to Done from any non-
            // terminal stage. StageDQueued already routes to Done in
            // the success path above.
            | (StageAQueued, Done)
            | (StageACommitted, Done)
            | (StageBInFlight { .. }, Done)
            | (StageBCommitted, Done)
            | (StageCQueued, Done)
            | (StageCCommitted, Done)
    )
}

impl Default for WritebackQueue {
    fn default() -> Self {
        Self::new()
    }
}

impl WritebackQueue {
    pub fn new() -> Self {
        Self {
            inner: Mutex::new(QueueInner {
                inode_intents: HashMap::new(),
                block_intents: HashMap::new(),
                parent_intents: HashMap::new(),
                inodes_by_parent: HashMap::new(),
                intents_by_stage: BTreeMap::new(),
                file_pipeline: HashMap::new(),
                active_generation: HashMap::new(),
                dep_predecessors: HashMap::new(),
                dep_dependents: HashMap::new(),
                errseq: HashMap::new(),
                pending_overlay: HashMap::new(),
                next_intent_id: 1,
                state: QueueState::default(),
            }),
        }
    }

    /// Update the inode-level pending overlay for a write that just
    /// happened on `inode`. The overlay aggregates across every fh
    /// open on the inode, so a different fh reading from the same
    /// inode (same fs_server instance) sees these bytes immediately.
    pub fn overlay_record_write(
        &self,
        inode: u64,
        block_num: u32,
        block_bytes: Bytes,
        new_file_size: u64,
    ) {
        let mut inner = self.inner.lock().expect("writeback queue poisoned");
        let entry = inner.pending_overlay.entry(inode).or_default();
        if new_file_size > entry.file_size {
            entry.file_size = new_file_size;
        }
        entry
            .blocks
            .insert(block_num, OverlayBlockState::Rewrite(block_bytes));
    }

    /// Drop a block entry from the overlay because its corresponding
    /// `BlockIntent` has reached `Committed`.
    pub fn overlay_block_committed(&self, inode: u64, block_num: u32) {
        let mut inner = self.inner.lock().expect("writeback queue poisoned");
        if let Some(entry) = inner.pending_overlay.get_mut(&inode) {
            entry.blocks.remove(&block_num);
            // Whole inode idle? Drop the entry to keep the map small.
            if entry.blocks.is_empty() {
                inner.pending_overlay.remove(&inode);
            }
        }
    }

    /// Snapshot the overlay for an inode, if any.
    pub fn overlay_for(&self, inode: u64) -> Option<PendingOverlay> {
        let inner = self.inner.lock().expect("writeback queue poisoned");
        inner.pending_overlay.get(&inode).cloned()
    }

    /// `true` iff every cycle on `inode` at generation `<= barrier`
    /// has reached `Done`. The fsync drain loop polls this after
    /// scheduling work; a true return means the drain is complete.
    pub fn cycles_at_or_below_drained(&self, inode: u64, barrier: Generation) -> bool {
        let inner = self.inner.lock().expect("writeback queue poisoned");
        let Some(cycles) = inner.file_pipeline.get(&inode) else {
            return true;
        };
        cycles
            .iter()
            .filter(|(g, _)| **g <= barrier)
            .all(|(_, c)| c.stage == FileCommitStage::Done)
    }

    /// Block (or unblock) new enqueues. The unmount path sets this
    /// before draining so the queue depth is monotonically decreasing.
    pub fn set_enqueue_blocked(&self, blocked: bool) {
        let mut inner = self.inner.lock().expect("writeback queue poisoned");
        inner.state.enqueue_blocked = blocked;
    }

    /// Returns `true` if new FUSE ops should be rejected with
    /// ENOTCONN (unmount in progress).
    pub fn is_enqueue_blocked(&self) -> bool {
        let inner = self.inner.lock().expect("writeback queue poisoned");
        inner.state.enqueue_blocked
    }

    /// Mark every cycle at gen `<= barrier` on `inode` as `Done` for
    /// the unmount-with-timeout case. Surfaces a `Failed` count via
    /// `state.deferred_errors` so post-mortem logs can identify the
    /// abandoned work.
    pub fn abandon_cycles_below(&self, inode: u64, barrier: Generation) -> usize {
        let mut inner = self.inner.lock().expect("writeback queue poisoned");
        let Some(cycles) = inner.file_pipeline.get_mut(&inode) else {
            return 0;
        };
        let mut abandoned = 0usize;
        for (g, c) in cycles.iter_mut() {
            if *g <= barrier && c.stage != FileCommitStage::Done {
                c.stage = FileCommitStage::Done;
                abandoned += 1;
            }
        }
        if abandoned > 0 {
            inner.state.deferred_errors =
                inner.state.deferred_errors.saturating_add(abandoned as u64);
        }
        abandoned
    }

    /// Snapshot of queue telemetry. Cheap; intended for the metrics
    /// exporter.
    pub fn telemetry(&self) -> QueueState {
        self.inner.lock().expect("writeback queue poisoned").state
    }

    /// Active generation for an inode, or `Generation(0)` if none has
    /// been opened yet. Callers use this to key their per-block
    /// intents.
    pub fn active_generation(&self, inode: u64) -> Generation {
        let inner = self.inner.lock().expect("writeback queue poisoned");
        inner
            .active_generation
            .get(&inode)
            .copied()
            .unwrap_or(Generation(0))
    }

    /// Open a new cycle for `inode` at `generation`, recording the
    /// cycle's initial size. Used by FUSE_CREATE and the write path
    /// when the previous cycle's Stage A has reached its terminal
    /// stage (initial scope) or unconditionally (full target).
    pub fn open_cycle(&self, inode: u64, generation: Generation, file_size: u64, block_count: u32) {
        let mut inner = self.inner.lock().expect("writeback queue poisoned");
        inner.file_pipeline.entry(inode).or_default().insert(
            generation,
            CyclePipelineState::new(generation, file_size, block_count),
        );
        inner.active_generation.insert(inode, generation);
    }

    /// Update the cycle's `terminal_size` aggregate. Called by
    /// FUSE_WRITE for the active generation.
    pub fn note_write(
        &self,
        inode: u64,
        generation: Generation,
        new_file_size: u64,
        new_block_count: u32,
        fh: FhId,
    ) {
        let mut inner = self.inner.lock().expect("writeback queue poisoned");
        if let Some(cycles) = inner.file_pipeline.get_mut(&inode)
            && let Some(cycle) = cycles.get_mut(&generation)
        {
            cycle.note_write(new_file_size, new_block_count, fh);
        }
    }

    /// Inspect a cycle's current state (read-only). Used by tests and
    /// the FUSE op layer for diagnostic / decision logic.
    pub fn cycle_state(&self, inode: u64, generation: Generation) -> Option<CyclePipelineState> {
        let inner = self.inner.lock().expect("writeback queue poisoned");
        inner.file_pipeline.get(&inode)?.get(&generation).cloned()
    }

    /// Seal the cycle's `terminal_size` and advance its stage to
    /// `StageAQueued`. Called when the worker picks up Stage A for
    /// this generation (Pending -> InFlight transition).
    pub fn seal_cycle_for_stage_a(&self, inode: u64, generation: Generation) {
        let mut inner = self.inner.lock().expect("writeback queue poisoned");
        if let Some(cycles) = inner.file_pipeline.get_mut(&inode)
            && let Some(cycle) = cycles.get_mut(&generation)
        {
            cycle.seal();
            cycle.stage = FileCommitStage::StageAQueued;
        }
    }

    /// Upsert an `InodeIntent`. Applies the coalescing rules. Returns
    /// the outcome so callers can react (the write path uses
    /// `BackpressureRequired` to block the caller).
    pub fn upsert_inode_intent(
        &self,
        key: S3Key,
        generation: Generation,
        op: InodeOp,
        fh: FhId,
    ) -> CoalesceOutcome {
        let mut inner = self.inner.lock().expect("writeback queue poisoned");

        if let Some(existing) = inner.inode_intents.get_mut(&(key.clone(), generation)) {
            match existing.state {
                IntentState::Pending => {
                    let outcome = coalesce_inode_pending(&mut existing.op, &op);
                    if !existing.fhs.contains(&fh) {
                        existing.fhs.push(fh);
                    }
                    return outcome;
                }
                IntentState::InFlight => {
                    return CoalesceOutcome::BackpressureRequired;
                }
                IntentState::Committed | IntentState::Failed => {
                    // Stale entry; fall through to insert a fresh
                    // intent. The caller routes through `open_cycle`
                    // first, so this arm is mostly defensive.
                }
            }
        }

        let id = inner.alloc_intent_id();
        let parent_key = match &op {
            InodeOp::PutInode { parent_key, .. } => Some(parent_key.clone()),
            InodeOp::SetAttr { .. } => None,
        };
        let intent = InodeIntent {
            op,
            generation,
            deps: Vec::new(),
            state: IntentState::Pending,
            fhs: vec![fh],
            enqueued_at: Instant::now(),
        };
        inner
            .inode_intents
            .insert((key.clone(), generation), intent);
        inner
            .intents_by_stage
            .entry(Stage::A)
            .or_default()
            .insert(id);
        if let Some(parent) = parent_key {
            inner.inodes_by_parent.entry(parent).or_default().insert(id);
        }
        inner.state.depth = inner.state.depth.saturating_add(1);
        CoalesceOutcome::Inserted
    }

    /// Upsert a `BlockIntent` keyed by `(blob, block, gen)`.
    /// Coalesce rules: same key Pending ⇒ replace body+checksum in
    /// place; same key InFlight ⇒ `BackpressureRequired` (the caller
    /// blocks until the prior cycle's terminal stage).
    pub fn upsert_block_intent(
        &self,
        blob_id: DataBlobGuid,
        block_num: u32,
        generation: Generation,
        body: Bytes,
        checksum: u64,
        fh: FhId,
    ) -> CoalesceOutcome {
        let mut inner = self.inner.lock().expect("writeback queue poisoned");

        if let Some(existing) = inner
            .block_intents
            .get_mut(&(blob_id, block_num, generation))
        {
            match existing.state {
                IntentState::Pending => {
                    let BlockOp::PutDataBlob {
                        body: ref mut b,
                        checksum: ref mut c,
                        version,
                        ..
                    } = existing.op;
                    *b = body;
                    *c = checksum;
                    // Sanity: same generation implies same blob_version.
                    debug_assert_eq!(version, generation.0);
                    if !existing.fhs.contains(&fh) {
                        existing.fhs.push(fh);
                    }
                    return CoalesceOutcome::ReplacedInPlace;
                }
                IntentState::InFlight => {
                    return CoalesceOutcome::BackpressureRequired;
                }
                IntentState::Committed | IntentState::Failed => {
                    // Stale; fall through.
                }
            }
        }

        let id = inner.alloc_intent_id();
        let intent = BlockIntent {
            op: BlockOp::PutDataBlob {
                blob_id,
                block_num,
                version: generation.0,
                body,
                checksum,
            },
            generation,
            deps: Vec::new(),
            state: IntentState::Pending,
            fhs: vec![fh],
            enqueued_at: Instant::now(),
        };
        inner
            .block_intents
            .insert((blob_id, block_num, generation), intent);
        inner
            .intents_by_stage
            .entry(Stage::B)
            .or_default()
            .insert(id);
        inner.state.depth = inner.state.depth.saturating_add(1);
        CoalesceOutcome::Inserted
    }

    /// Snapshot the count of pending+inflight intents. Cheap.
    pub fn depth(&self) -> u64 {
        self.inner
            .lock()
            .expect("writeback queue poisoned")
            .state
            .depth
    }

    /// Advance a cycle's pipeline stage. The transitions follow the
    /// ordered A->B->C->D walk; out-of-order advances are rejected via
    /// `Result` so callers can surface a programmer error (rather than
    /// silently violating the per-file ordering invariant).
    pub fn advance_stage(
        &self,
        inode: u64,
        generation: Generation,
        new_stage: FileCommitStage,
    ) -> Result<(), StageAdvanceError> {
        let mut inner = self.inner.lock().expect("writeback queue poisoned");
        let cycle = inner
            .file_pipeline
            .get_mut(&inode)
            .and_then(|c| c.get_mut(&generation))
            .ok_or(StageAdvanceError::CycleMissing)?;
        if !is_valid_stage_transition(cycle.stage, new_stage) {
            return Err(StageAdvanceError::InvalidTransition {
                from: cycle.stage,
                to: new_stage,
            });
        }
        cycle.stage = new_stage;
        Ok(())
    }

    /// Capture a fsync barrier: the highest dirty generation for
    /// `inode` at this instant. Returns `None` when no cycle is
    /// dirty (a fsync(fd) on an idle inode is a no-op).
    pub fn fsync_barrier(&self, inode: u64) -> Option<Generation> {
        let inner = self.inner.lock().expect("writeback queue poisoned");
        inner
            .file_pipeline
            .get(&inode)?
            .keys()
            .filter(|g| {
                inner
                    .file_pipeline
                    .get(&inode)
                    .and_then(|m| m.get(g))
                    .is_some_and(|c| c.stage != FileCommitStage::Done)
            })
            .max()
            .copied()
    }

    /// Record a deferred error against the inode and bump its
    /// per-inode errseq so a subsequent fsync / close on any fh that
    /// has not yet observed it surfaces EIO.
    pub fn record_failure(&self, inode: u64, _generation: Generation) {
        let mut inner = self.inner.lock().expect("writeback queue poisoned");
        inner.state.deferred_errors = inner.state.deferred_errors.saturating_add(1);
        let entry = inner.errseq.entry(inode).or_default();
        entry.errseq = entry.errseq.wrapping_add(1);
        entry.tainted = true;
    }

    /// Read the inode's errseq counter (the value an fh compares
    /// against its `last_seen_errseq` to decide whether a new error
    /// should surface).
    pub fn errseq(&self, inode: u64) -> u32 {
        let inner = self.inner.lock().expect("writeback queue poisoned");
        inner.errseq.get(&inode).map(|e| e.errseq).unwrap_or(0)
    }

    /// `true` iff a Stage A failure (CAS conflict / unknown outcome
    /// / max-inflight expiry) has tainted this inode. Tainted inodes
    /// must close-and-reopen to observe the remote winner; further
    /// writes on the existing handle continue to surface EIO.
    pub fn is_tainted(&self, inode: u64) -> bool {
        let inner = self.inner.lock().expect("writeback queue poisoned");
        inner.errseq.get(&inode).map(|e| e.tainted).unwrap_or(false)
    }

    /// Per-fh fsyncgate / errseq probe: returns `Some(new_errseq)` if
    /// the inode's errseq has advanced beyond `last_seen` (caller
    /// updates its `last_seen` and surfaces EIO). `None` means no
    /// new error since last check.
    pub fn check_errseq(&self, inode: u64, last_seen: u32) -> Option<u32> {
        let inner = self.inner.lock().expect("writeback queue poisoned");
        let cur = inner.errseq.get(&inode).map(|e| e.errseq).unwrap_or(0);
        if cur != last_seen { Some(cur) } else { None }
    }

    /// Add an ancestor / predecessor dependency edge from `dependent`
    /// to `predecessor`. The dep tracker holds entries until the
    /// predecessor reaches `Committed`; a worker scanning Stage A can
    /// skip a Pending intent whose `unmet_deps > 0`.
    pub fn add_dep(&self, dependent: IntentId, predecessor: IntentId) {
        let mut inner = self.inner.lock().expect("writeback queue poisoned");
        inner
            .dep_predecessors
            .entry(dependent)
            .or_default()
            .insert(predecessor);
        inner
            .dep_dependents
            .entry(predecessor)
            .or_default()
            .insert(dependent);
    }

    /// Number of unmet predecessors for `dependent`. Zero means the
    /// intent's deps are satisfied and a worker may pick it up.
    pub fn unmet_deps(&self, dependent: IntentId) -> usize {
        let inner = self.inner.lock().expect("writeback queue poisoned");
        inner
            .dep_predecessors
            .get(&dependent)
            .map(|s| s.len())
            .unwrap_or(0)
    }

    /// Mark a predecessor as committed; remove it from each of its
    /// dependents' predecessor sets. Returns the dependents that
    /// became unblocked (their predecessor sets are now empty) so the
    /// caller can wake / requeue them.
    pub fn mark_predecessor_committed(&self, predecessor: IntentId) -> Vec<IntentId> {
        let mut inner = self.inner.lock().expect("writeback queue poisoned");
        let dependents = inner
            .dep_dependents
            .remove(&predecessor)
            .unwrap_or_default();
        let mut unblocked = Vec::new();
        for d in dependents {
            if let Some(preds) = inner.dep_predecessors.get_mut(&d) {
                preds.remove(&predecessor);
                if preds.is_empty() {
                    inner.dep_predecessors.remove(&d);
                    unblocked.push(d);
                }
            }
        }
        unblocked
    }

    /// Group requeue across the transitive dependent closure of
    /// `failed`. Walks `dep_dependents` graph to collect every entry
    /// reachable from `failed`. Useful for the in-batch
    /// `DEPENDENCY_FAILED` rule.
    pub fn transitive_dependent_closure(&self, failed: IntentId) -> Vec<IntentId> {
        let inner = self.inner.lock().expect("writeback queue poisoned");
        let mut out = Vec::new();
        let mut frontier = vec![failed];
        let mut seen: BTreeSet<IntentId> = BTreeSet::new();
        seen.insert(failed);
        while let Some(cur) = frontier.pop() {
            if cur != failed {
                out.push(cur);
            }
            if let Some(deps) = inner.dep_dependents.get(&cur) {
                for d in deps {
                    if seen.insert(*d) {
                        frontier.push(*d);
                    }
                }
            }
        }
        out
    }

    /// Drain helper for tests: pop every Pending intent at `stage`
    /// and mark them `InFlight`. Returns the popped intents in
    /// insertion order. The real worker uses a richer
    /// dep-aware variant.
    #[cfg(test)]
    pub fn pop_pending_for_stage(&self, stage: Stage) -> Vec<IntentSnapshot> {
        let mut inner = self.inner.lock().expect("writeback queue poisoned");
        let mut out = Vec::new();
        match stage {
            Stage::A => {
                let keys: Vec<_> = inner
                    .inode_intents
                    .iter()
                    .filter(|(_, v)| v.state == IntentState::Pending)
                    .map(|(k, _)| k.clone())
                    .collect();
                for key in keys {
                    let intent = inner.inode_intents.get_mut(&key).expect("present");
                    intent.state = IntentState::InFlight;
                    out.push(IntentSnapshot::Inode(intent.clone()));
                }
            }
            Stage::B => {
                let keys: Vec<_> = inner
                    .block_intents
                    .iter()
                    .filter(|(_, v)| v.state == IntentState::Pending)
                    .map(|(k, _)| *k)
                    .collect();
                for key in keys {
                    let intent = inner.block_intents.get_mut(&key).expect("present");
                    intent.state = IntentState::InFlight;
                    out.push(IntentSnapshot::Block(intent.clone()));
                }
            }
            _ => {}
        }
        out
    }
}

#[cfg(test)]
#[derive(Debug, Clone)]
pub enum IntentSnapshot {
    Inode(InodeIntent),
    Block(BlockIntent),
}

impl QueueInner {
    fn alloc_intent_id(&mut self) -> IntentId {
        let id = IntentId(self.next_intent_id);
        self.next_intent_id += 1;
        id
    }
}

/// Inode-intent Pending coalescing rules. Returns the outcome and
/// mutates `existing` in place when a merge is possible. Pairs not
/// covered here fall back to inserting a successor intent -- but the
/// initial enabled op set (PutInode + SetAttr) keeps every
/// coalescable combination here.
fn coalesce_inode_pending(existing: &mut InodeOp, new: &InodeOp) -> CoalesceOutcome {
    match (&mut *existing, new) {
        // PutInode + PutInode (same key) ⇒ replace the layout in
        // place (latest wins). Uncommon because FUSE_CREATE is unique
        // per path, but defensive.
        (
            InodeOp::PutInode { .. },
            InodeOp::PutInode {
                parent_key,
                name,
                layout_bytes,
            },
        ) => {
            *existing = InodeOp::PutInode {
                parent_key: parent_key.clone(),
                name: name.clone(),
                layout_bytes: layout_bytes.clone(),
            };
            CoalesceOutcome::ReplacedInPlace
        }
        // PutInode + SetAttr ⇒ Merged. The worker applies the attr
        // mutation when it ships Stage A.
        (InodeOp::PutInode { .. }, InodeOp::SetAttr { .. }) => CoalesceOutcome::Merged,
        // SetAttr + SetAttr ⇒ field-merge.
        (
            InodeOp::SetAttr {
                attrs: existing_attrs,
                ..
            },
            InodeOp::SetAttr {
                attrs: new_attrs, ..
            },
        ) => {
            existing_attrs.merge_from(new_attrs);
            CoalesceOutcome::Merged
        }
        // SetAttr + PutInode shouldn't happen (PutInode is the
        // creation op; if we have a SetAttr Pending, the create
        // already committed). Treat as a successor.
        (InodeOp::SetAttr { .. }, InodeOp::PutInode { .. }) => CoalesceOutcome::Inserted,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use uuid::Uuid;

    fn dummy_blob() -> DataBlobGuid {
        DataBlobGuid {
            blob_id: Uuid::from_u128(0xdead_beef),
            volume_id: 1,
        }
    }

    #[test]
    fn open_cycle_records_initial_state() {
        let q = WritebackQueue::new();
        q.open_cycle(42, Generation(7), 1024, 8);
        let st = q.cycle_state(42, Generation(7)).expect("cycle present");
        assert_eq!(st.generation, Generation(7));
        assert_eq!(st.stage, FileCommitStage::Idle);
        assert_eq!(st.terminal_size.file_size(), 1024);
        assert_eq!(st.terminal_size.block_count(), 8);
        assert!(!st.terminal_size.is_sealed());
        assert_eq!(q.active_generation(42), Generation(7));
    }

    #[test]
    fn note_write_grows_terminal_size_and_tracks_contributors() {
        let q = WritebackQueue::new();
        q.open_cycle(1, Generation(0), 0, 0);
        q.note_write(1, Generation(0), 4096, 1, FhId(11));
        q.note_write(1, Generation(0), 8192, 2, FhId(12));
        // Smaller follow-up does not shrink terminal_size.
        q.note_write(1, Generation(0), 100, 1, FhId(11));
        let st = q.cycle_state(1, Generation(0)).unwrap();
        assert_eq!(st.terminal_size.file_size(), 8192);
        assert_eq!(st.terminal_size.block_count(), 2);
        assert!(st.contributors.contains(&FhId(11)));
        assert!(st.contributors.contains(&FhId(12)));
    }

    #[test]
    fn seal_cycle_freezes_terminal_size() {
        let q = WritebackQueue::new();
        q.open_cycle(1, Generation(0), 100, 1);
        q.note_write(1, Generation(0), 200, 2, FhId(11));
        q.seal_cycle_for_stage_a(1, Generation(0));

        let st = q.cycle_state(1, Generation(0)).unwrap();
        assert!(st.terminal_size.is_sealed());
        assert_eq!(st.terminal_size.file_size(), 200);

        // Post-seal writes are ignored by terminal_size; the queue's
        // backpressure layer prevents new intents at this generation
        // from landing.
        q.note_write(1, Generation(0), 999, 9, FhId(11));
        let st2 = q.cycle_state(1, Generation(0)).unwrap();
        assert_eq!(st2.terminal_size.file_size(), 200);
        assert_eq!(st2.terminal_size.block_count(), 2);
    }

    #[test]
    fn upsert_block_intent_replaces_body_in_place_for_same_key_same_gen() {
        let q = WritebackQueue::new();
        let blob = dummy_blob();

        let r1 = q.upsert_block_intent(
            blob,
            5,
            Generation(0),
            Bytes::from_static(b"first"),
            0xaaaa,
            FhId(1),
        );
        assert_eq!(r1, CoalesceOutcome::Inserted);
        assert_eq!(q.depth(), 1);

        let r2 = q.upsert_block_intent(
            blob,
            5,
            Generation(0),
            Bytes::from_static(b"second"),
            0xbbbb,
            FhId(1),
        );
        assert_eq!(r2, CoalesceOutcome::ReplacedInPlace);
        // Depth unchanged — coalesced.
        assert_eq!(q.depth(), 1);

        // The new body wins.
        let popped = q.pop_pending_for_stage(Stage::B);
        assert_eq!(popped.len(), 1);
        match &popped[0] {
            IntentSnapshot::Block(b) => match &b.op {
                BlockOp::PutDataBlob { body, checksum, .. } => {
                    assert_eq!(&body[..], b"second");
                    assert_eq!(*checksum, 0xbbbb);
                }
            },
            _ => panic!("expected block"),
        }
    }

    #[test]
    fn upsert_block_intent_distinct_keys_each_increment_depth() {
        let q = WritebackQueue::new();
        let blob = dummy_blob();
        for block in 0..16 {
            q.upsert_block_intent(
                blob,
                block,
                Generation(0),
                Bytes::from_static(b"x"),
                0,
                FhId(1),
            );
        }
        assert_eq!(q.depth(), 16);
    }

    #[test]
    fn block_intents_at_different_generations_do_not_coalesce() {
        let q = WritebackQueue::new();
        let blob = dummy_blob();
        q.upsert_block_intent(
            blob,
            0,
            Generation(0),
            Bytes::from_static(b"v0"),
            0,
            FhId(1),
        );
        q.upsert_block_intent(
            blob,
            0,
            Generation(1),
            Bytes::from_static(b"v1"),
            0,
            FhId(1),
        );
        // Two distinct intents — different generations.
        assert_eq!(q.depth(), 2);
    }

    #[test]
    fn upsert_block_intent_inflight_returns_backpressure_required() {
        let q = WritebackQueue::new();
        let blob = dummy_blob();
        q.upsert_block_intent(
            blob,
            0,
            Generation(0),
            Bytes::from_static(b"first"),
            0,
            FhId(1),
        );
        // Pop pending → InFlight.
        let _ = q.pop_pending_for_stage(Stage::B);

        let r = q.upsert_block_intent(
            blob,
            0,
            Generation(0),
            Bytes::from_static(b"second"),
            0,
            FhId(1),
        );
        assert_eq!(r, CoalesceOutcome::BackpressureRequired);
        // Depth unchanged.
        assert_eq!(q.depth(), 1);
    }

    #[test]
    fn upsert_inode_intent_inserts_then_replaces_pending_putinode() {
        let q = WritebackQueue::new();
        let key = "/a/b".to_string();
        let r1 = q.upsert_inode_intent(
            key.clone(),
            Generation(0),
            InodeOp::PutInode {
                parent_key: "/a".to_string(),
                name: "b".to_string(),
                layout_bytes: Bytes::from_static(b"v1"),
            },
            FhId(1),
        );
        assert_eq!(r1, CoalesceOutcome::Inserted);
        assert_eq!(q.depth(), 1);

        let r2 = q.upsert_inode_intent(
            key.clone(),
            Generation(0),
            InodeOp::PutInode {
                parent_key: "/a".to_string(),
                name: "b".to_string(),
                layout_bytes: Bytes::from_static(b"v2"),
            },
            FhId(1),
        );
        assert_eq!(r2, CoalesceOutcome::ReplacedInPlace);
        assert_eq!(q.depth(), 1);
    }

    #[test]
    fn upsert_inode_intent_setattr_setattr_field_merges() {
        let q = WritebackQueue::new();
        let key = "/foo".to_string();
        let r1 = q.upsert_inode_intent(
            key.clone(),
            Generation(0),
            InodeOp::SetAttr {
                key: key.clone(),
                attrs: AttrMutation {
                    mode: Some(0o644),
                    ..Default::default()
                },
            },
            FhId(1),
        );
        assert_eq!(r1, CoalesceOutcome::Inserted);

        let r2 = q.upsert_inode_intent(
            key.clone(),
            Generation(0),
            InodeOp::SetAttr {
                key: key.clone(),
                attrs: AttrMutation {
                    uid: Some(1000),
                    ..Default::default()
                },
            },
            FhId(1),
        );
        assert_eq!(r2, CoalesceOutcome::Merged);
        assert_eq!(q.depth(), 1);

        // The merged entry must carry both fields.
        let popped = q.pop_pending_for_stage(Stage::A);
        assert_eq!(popped.len(), 1);
        match &popped[0] {
            IntentSnapshot::Inode(InodeIntent {
                op: InodeOp::SetAttr { attrs, .. },
                ..
            }) => {
                assert_eq!(attrs.mode, Some(0o644));
                assert_eq!(attrs.uid, Some(1000));
            }
            _ => panic!("expected setattr inode intent"),
        }
    }

    #[test]
    fn attr_mutation_merge_from_overrides_only_populated_fields() {
        let mut a = AttrMutation {
            mode: Some(0o600),
            uid: Some(0),
            ..Default::default()
        };
        let b = AttrMutation {
            uid: Some(1000),
            atime_secs: Some(42),
            ..Default::default()
        };
        a.merge_from(&b);
        assert_eq!(a.mode, Some(0o600)); // preserved from a
        assert_eq!(a.uid, Some(1000)); // overridden
        assert_eq!(a.atime_secs, Some(42)); // adopted
        assert!(!a.is_empty());
    }

    #[test]
    fn telemetry_reflects_depth() {
        let q = WritebackQueue::new();
        let blob = dummy_blob();
        for i in 0..5 {
            q.upsert_block_intent(blob, i, Generation(0), Bytes::from_static(b"x"), 0, FhId(1));
        }
        assert_eq!(q.telemetry().depth, 5);
    }

    #[test]
    fn fhs_set_unions_across_coalesced_writes() {
        let q = WritebackQueue::new();
        let blob = dummy_blob();
        q.upsert_block_intent(blob, 0, Generation(0), Bytes::from_static(b"a"), 0, FhId(1));
        q.upsert_block_intent(blob, 0, Generation(0), Bytes::from_static(b"b"), 0, FhId(2));
        let popped = q.pop_pending_for_stage(Stage::B);
        match &popped[0] {
            IntentSnapshot::Block(b) => {
                assert!(b.fhs.contains(&FhId(1)));
                assert!(b.fhs.contains(&FhId(2)));
            }
            _ => panic!("expected block"),
        }
    }

    /// `_uuid_alias` keeps the import audit-trail explicit.
    #[allow(dead_code)]
    fn _uuid_alias() -> Uuid {
        Uuid::from_u128(0)
    }

    // ── Stage advancement ───────────────────────────────────────────

    #[test]
    fn stage_advance_walks_a_b_c_d_in_order() {
        let q = WritebackQueue::new();
        q.open_cycle(1, Generation(0), 0, 0);
        let g = Generation(0);

        q.advance_stage(1, g, FileCommitStage::StageAQueued)
            .unwrap();
        q.advance_stage(1, g, FileCommitStage::StageACommitted)
            .unwrap();
        q.advance_stage(
            1,
            g,
            FileCommitStage::StageBInFlight {
                blocks_remaining: 4,
            },
        )
        .unwrap();
        // Block-fanout decrement is also a valid B->B transition.
        q.advance_stage(
            1,
            g,
            FileCommitStage::StageBInFlight {
                blocks_remaining: 0,
            },
        )
        .unwrap();
        q.advance_stage(1, g, FileCommitStage::StageBCommitted)
            .unwrap();
        q.advance_stage(1, g, FileCommitStage::StageCQueued)
            .unwrap();
        q.advance_stage(1, g, FileCommitStage::StageCCommitted)
            .unwrap();
        q.advance_stage(1, g, FileCommitStage::StageDQueued)
            .unwrap();
        q.advance_stage(1, g, FileCommitStage::Done).unwrap();

        let st = q.cycle_state(1, g).unwrap();
        assert_eq!(st.stage, FileCommitStage::Done);
    }

    #[test]
    fn stage_advance_rejects_skip_or_reverse() {
        let q = WritebackQueue::new();
        q.open_cycle(1, Generation(0), 0, 0);
        let g = Generation(0);
        // Skipping A->C is rejected.
        let bad = q.advance_stage(1, g, FileCommitStage::StageCQueued);
        assert!(matches!(
            bad,
            Err(StageAdvanceError::InvalidTransition { .. })
        ));
        // After legitimate A->A_committed, advancing back to A is rejected.
        q.advance_stage(1, g, FileCommitStage::StageAQueued)
            .unwrap();
        q.advance_stage(1, g, FileCommitStage::StageACommitted)
            .unwrap();
        let reverse = q.advance_stage(1, g, FileCommitStage::StageAQueued);
        assert!(matches!(
            reverse,
            Err(StageAdvanceError::InvalidTransition { .. })
        ));
    }

    #[test]
    fn stage_advance_missing_cycle_errors() {
        let q = WritebackQueue::new();
        let r = q.advance_stage(1, Generation(0), FileCommitStage::StageAQueued);
        assert_eq!(r, Err(StageAdvanceError::CycleMissing));
    }

    #[test]
    fn failed_cycle_can_short_circuit_to_done_from_any_stage() {
        for from in [
            FileCommitStage::StageAQueued,
            FileCommitStage::StageACommitted,
            FileCommitStage::StageBInFlight {
                blocks_remaining: 1,
            },
            FileCommitStage::StageBCommitted,
            FileCommitStage::StageCQueued,
            FileCommitStage::StageCCommitted,
            FileCommitStage::StageDQueued,
        ] {
            assert!(
                is_valid_stage_transition(from, FileCommitStage::Done),
                "{:?} -> Done must be valid",
                from
            );
        }
    }

    // ── Fsync barrier ───────────────────────────────────────────────

    #[test]
    fn fsync_barrier_returns_max_dirty_generation() {
        let q = WritebackQueue::new();
        q.open_cycle(7, Generation(2), 100, 1);
        // Manually plant a higher dirty generation by opening another
        // cycle on the same inode (full-target shape).
        q.open_cycle(7, Generation(5), 200, 2);
        // Mark cycle 2 as Done so it should not factor into the barrier.
        q.advance_stage(7, Generation(2), FileCommitStage::StageAQueued)
            .unwrap();
        q.advance_stage(7, Generation(2), FileCommitStage::Done)
            .unwrap();

        let barrier = q.fsync_barrier(7);
        assert_eq!(barrier, Some(Generation(5)));
    }

    #[test]
    fn fsync_barrier_none_for_idle_inode() {
        let q = WritebackQueue::new();
        assert_eq!(q.fsync_barrier(99), None);
    }

    // ── Errseq + taint ──────────────────────────────────────────────

    #[test]
    fn record_failure_bumps_errseq_and_taints() {
        let q = WritebackQueue::new();
        assert_eq!(q.errseq(1), 0);
        assert!(!q.is_tainted(1));
        q.record_failure(1, Generation(0));
        assert_eq!(q.errseq(1), 1);
        assert!(q.is_tainted(1));
        // A fh that has already seen errseq=1 sees None.
        assert_eq!(q.check_errseq(1, 1), None);
        // A fh at last_seen=0 sees the new errseq.
        assert_eq!(q.check_errseq(1, 0), Some(1));
        q.record_failure(1, Generation(0));
        assert_eq!(q.errseq(1), 2);
    }

    #[test]
    fn errseq_per_inode() {
        let q = WritebackQueue::new();
        q.record_failure(1, Generation(0));
        q.record_failure(2, Generation(0));
        q.record_failure(2, Generation(0));
        assert_eq!(q.errseq(1), 1);
        assert_eq!(q.errseq(2), 2);
        assert!(q.is_tainted(1));
        assert!(q.is_tainted(2));
        assert!(!q.is_tainted(3));
    }

    // ── Dependency DAG ──────────────────────────────────────────────

    #[test]
    fn dep_tracker_unblocks_dependent_after_predecessor_commits() {
        let q = WritebackQueue::new();
        let mkdir = IntentId(10);
        let creat = IntentId(11);
        q.add_dep(creat, mkdir);
        assert_eq!(q.unmet_deps(creat), 1);
        let unblocked = q.mark_predecessor_committed(mkdir);
        assert_eq!(unblocked, vec![creat]);
        assert_eq!(q.unmet_deps(creat), 0);
    }

    #[test]
    fn dep_tracker_multi_predecessor() {
        let q = WritebackQueue::new();
        let p1 = IntentId(1);
        let p2 = IntentId(2);
        let p3 = IntentId(3);
        let d = IntentId(99);
        q.add_dep(d, p1);
        q.add_dep(d, p2);
        q.add_dep(d, p3);
        assert_eq!(q.unmet_deps(d), 3);
        // Commit p1: dependent still has 2 unmet.
        assert!(q.mark_predecessor_committed(p1).is_empty());
        assert_eq!(q.unmet_deps(d), 2);
        // Commit p2 and p3: d is unblocked only on the last.
        assert!(q.mark_predecessor_committed(p2).is_empty());
        let unblocked = q.mark_predecessor_committed(p3);
        assert_eq!(unblocked, vec![d]);
        assert_eq!(q.unmet_deps(d), 0);
    }

    #[test]
    fn transitive_dependent_closure_walks_chain() {
        let q = WritebackQueue::new();
        // Chain: a -> b -> c (b depends on a; c depends on b).
        let a = IntentId(1);
        let b = IntentId(2);
        let c = IntentId(3);
        q.add_dep(b, a);
        q.add_dep(c, b);
        let mut closure = q.transitive_dependent_closure(a);
        closure.sort();
        assert_eq!(closure, vec![b, c]);
    }

    #[test]
    fn transitive_dependent_closure_empty_for_isolated() {
        let q = WritebackQueue::new();
        assert!(q.transitive_dependent_closure(IntentId(42)).is_empty());
    }

    // ── Pending-data overlay ────────────────────────────────────────

    #[test]
    fn overlay_records_writes_and_grows_file_size() {
        let q = WritebackQueue::new();
        q.overlay_record_write(1, 0, Bytes::from_static(b"abcd"), 4);
        q.overlay_record_write(1, 1, Bytes::from_static(b"xyzw"), 8);
        // Smaller follow-up does not shrink file_size.
        q.overlay_record_write(1, 0, Bytes::from_static(b"ABCD"), 1);

        let ov = q.overlay_for(1).unwrap();
        assert_eq!(ov.file_size, 8);
        assert_eq!(ov.lookup_block(0).unwrap().as_ref(), b"ABCD");
        assert_eq!(ov.lookup_block(1).unwrap().as_ref(), b"xyzw");
        assert!(ov.lookup_block(2).is_none());
        assert!(!ov.block_is_hole(0));
    }

    #[test]
    fn overlay_clears_on_block_committed_and_drops_when_empty() {
        let q = WritebackQueue::new();
        q.overlay_record_write(1, 0, Bytes::from_static(b"x"), 1);
        q.overlay_record_write(1, 1, Bytes::from_static(b"y"), 2);
        assert!(q.overlay_for(1).is_some());

        q.overlay_block_committed(1, 0);
        assert!(q.overlay_for(1).unwrap().lookup_block(0).is_none());
        assert!(q.overlay_for(1).unwrap().lookup_block(1).is_some());

        q.overlay_block_committed(1, 1);
        assert!(q.overlay_for(1).is_none(), "empty overlay must be dropped");
    }

    #[test]
    fn overlay_isolation_between_inodes() {
        let q = WritebackQueue::new();
        q.overlay_record_write(1, 0, Bytes::from_static(b"a"), 1);
        q.overlay_record_write(2, 0, Bytes::from_static(b"b"), 1);
        assert_eq!(
            q.overlay_for(1).unwrap().lookup_block(0).unwrap().as_ref(),
            b"a"
        );
        assert_eq!(
            q.overlay_for(2).unwrap().lookup_block(0).unwrap().as_ref(),
            b"b"
        );
    }

    #[test]
    fn overlay_block_is_hole_works_for_delete_state() {
        let mut ov = PendingOverlay {
            file_size: 4096,
            blocks: BTreeMap::new(),
        };
        ov.blocks.insert(7, OverlayBlockState::Delete);
        assert!(ov.block_is_hole(7));
        assert!(ov.lookup_block(7).is_none()); // Delete is not a Bytes lookup hit
    }

    // ── Sync drains ─────────────────────────────────────────────────

    #[test]
    fn cycles_at_or_below_drained_reports_correctly() {
        let q = WritebackQueue::new();
        q.open_cycle(1, Generation(0), 100, 1);
        q.open_cycle(1, Generation(1), 200, 2);
        q.open_cycle(1, Generation(2), 300, 3);

        // Nothing Done yet.
        assert!(!q.cycles_at_or_below_drained(1, Generation(2)));

        // Mark gen 0 + 1 Done; barrier=1 should drain.
        for g in [Generation(0), Generation(1)] {
            q.advance_stage(1, g, FileCommitStage::StageAQueued)
                .unwrap();
            q.advance_stage(1, g, FileCommitStage::Done).unwrap();
        }
        assert!(q.cycles_at_or_below_drained(1, Generation(1)));
        // Barrier=2 still not drained: gen 2 is dirty.
        assert!(!q.cycles_at_or_below_drained(1, Generation(2)));

        // Idle inode is trivially drained.
        assert!(q.cycles_at_or_below_drained(99, Generation(0)));
    }

    #[test]
    fn enqueue_blocked_flag_round_trips() {
        let q = WritebackQueue::new();
        assert!(!q.is_enqueue_blocked());
        q.set_enqueue_blocked(true);
        assert!(q.is_enqueue_blocked());
        q.set_enqueue_blocked(false);
        assert!(!q.is_enqueue_blocked());
    }

    #[test]
    fn abandon_cycles_below_marks_done_and_bumps_deferred_errors() {
        let q = WritebackQueue::new();
        q.open_cycle(1, Generation(0), 0, 0);
        q.open_cycle(1, Generation(1), 0, 0);
        q.advance_stage(1, Generation(0), FileCommitStage::StageAQueued)
            .unwrap();
        q.advance_stage(1, Generation(1), FileCommitStage::StageAQueued)
            .unwrap();

        let abandoned = q.abandon_cycles_below(1, Generation(1));
        assert_eq!(abandoned, 2);
        let st = q.cycle_state(1, Generation(0)).unwrap();
        assert_eq!(st.stage, FileCommitStage::Done);
        let st1 = q.cycle_state(1, Generation(1)).unwrap();
        assert_eq!(st1.stage, FileCommitStage::Done);
        assert_eq!(q.telemetry().deferred_errors, 2);
    }
}
